// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/morninng/z-go-react-monorepo/internal/interfaces/handlers"
)

// Injectors from wire.go:

func InitializeTaskHandler() *handlers.TaskHandler {
	taskHandler := handlers.NewTaskHandler()
	return taskHandler
}
