// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/morninng/z-go-react-monorepo/internal/application"
	"github.com/morninng/z-go-react-monorepo/internal/infrastructure/datastore"
	"github.com/morninng/z-go-react-monorepo/internal/interfaces/handlers"
)

// Injectors from wire.go:

func InitializeTaskHandler() *handlers.TaskHandler {
	db := datastore.NewDB()
	taskRepository := datastore.NewTaskRepository(db)
	taskApplicationService := application.NewTaskApplicationService(taskRepository)
	taskHandler := handlers.NewTaskHandler(taskApplicationService)
	return taskHandler
}
