// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.2 DO NOT EDIT.
package dto

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for BadRequestErrorCodeEnum.
const (
	BadRequestErrorCodeEnumInvalidJson      BadRequestErrorCodeEnum = "invalid_json"
	BadRequestErrorCodeEnumInvalidParameter BadRequestErrorCodeEnum = "invalid_parameter"
	BadRequestErrorCodeEnumInvalidToken     BadRequestErrorCodeEnum = "invalid_token"
)

// Defines values for ErrorCodeEnum.
const (
	AlreadyExists       ErrorCodeEnum = "already_exists"
	InternalServerError ErrorCodeEnum = "internal_server_error"
	NotFound            ErrorCodeEnum = "not_found"
)

// Defines values for ForbiddenErrorCodeEnum.
const (
	NotAllowed ForbiddenErrorCodeEnum = "not_allowed"
)

// Defines values for UnauthorizedErrorCodeEnum.
const (
	UnauthorizedErrorCodeEnumExpiredToken UnauthorizedErrorCodeEnum = "expired_token"
	UnauthorizedErrorCodeEnumInvalidToken UnauthorizedErrorCodeEnum = "invalid_token"
)

// BadRequestError 400番エラー
type BadRequestError struct {
	// Code 400番エラーのコード
	Code    BadRequestErrorCodeEnum `json:"code"`
	Message string                  `json:"message"`
}

// BadRequestErrorCodeEnum 400番エラーのコード
type BadRequestErrorCodeEnum string

// Error defines model for Error.
type Error struct {
	Code    ErrorCodeEnum `json:"code"`
	Message string        `json:"message"`
}

// ErrorCodeEnum defines model for ErrorCodeEnum.
type ErrorCodeEnum string

// ForbiddenError 403番エラー
type ForbiddenError struct {
	// Code 403番のエラーコード
	Code    ForbiddenErrorCodeEnum `json:"code"`
	Message string                 `json:"message"`
}

// ForbiddenErrorCodeEnum 403番のエラーコード
type ForbiddenErrorCodeEnum string

// Task タスク
type Task struct {
	// Constent タスクの内容
	Constent string             `json:"constent"`
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
}

// Tasks タスク群
type Tasks = []Task

// UnauthorizedError 401(認証)番エラー
type UnauthorizedError struct {
	// Code 401(認証)番のエラーコード
	Code    UnauthorizedErrorCodeEnum `json:"code"`
	Message string                    `json:"message"`
}

// UnauthorizedErrorCodeEnum 401(認証)番のエラーコード
type UnauthorizedErrorCodeEnum string

// TasksTaskId defines model for TasksTaskId.
type TasksTaskId = string
