// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.2 DO NOT EDIT.
package dto

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ErrorCodeEnum.
const (
	AlreadyExists       ErrorCodeEnum = "already_exists"
	InternalServerError ErrorCodeEnum = "internal_server_error"
	NotFound            ErrorCodeEnum = "not_found"
)

// Defines values for UnauthorizedErrorCodeEnum.
const (
	ExpiredToken UnauthorizedErrorCodeEnum = "expired_token"
	InvalidToken UnauthorizedErrorCodeEnum = "invalid_token"
)

// Error defines model for Error.
type Error struct {
	Code    ErrorCodeEnum `json:"code"`
	Message string        `json:"message"`
}

// ErrorCodeEnum defines model for ErrorCodeEnum.
type ErrorCodeEnum string

// Task タスク
type Task struct {
	// Constent タスクの内容
	Constent string             `json:"constent"`
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
}

// UnauthorizedError 401(認証)番エラー
type UnauthorizedError struct {
	// Code 401(認証)番のエラーコード
	Code    UnauthorizedErrorCodeEnum `json:"code"`
	Message string                    `json:"message"`
}

// UnauthorizedErrorCodeEnum 401(認証)番のエラーコード
type UnauthorizedErrorCodeEnum string

// TasksTaskId defines model for TasksTaskId.
type TasksTaskId = string
